# .github/workflows/deploy-main.yml
name: Deploy Frontend to AWS Amplify Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: ./meetup-app  # Ange r채tt arbetskatalog
      run: npm install

    - name: Build the app
      working-directory: ./meetup-app  # Ange r채tt arbetskatalog
      run: npm run build

    - name: Install Amplify CLI
      working-directory: ./meetup-app  # Ange r채tt arbetskatalog
      run: npm install -g @aws-amplify/cli

    - name: Deploy to AWS Amplify
      working-directory: ./meetup-app  # Ange r채tt arbetskatalog
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-north-1'
      run: amplify publish
