name: Build and Deploy to Dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Använd den senaste versionen

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Deploy
      run: |
        echo "Deploy your app to Dev environment here"
