name: Deploy to AWS Amplify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Bytt till Node.js version 20

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Install Amplify CLI
      run: npm install -g @aws-amplify/cli  # Installera Amplify CLI

    - name: Deploy to AWS Amplify
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-north-1'  # Ersätt med din region om det behövs
      run: |
        # Installera AWS CLI om det inte redan finns
        pip install awscli

        # Konfigurera AWS CLI
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set region $AWS_REGION

        # Deploya till AWS Amplify med verbose output
        amplify publish --verbose
